version: "3.1"
services:
  keycloak:
    image: quay.io/keycloak/keycloak

    container_name: keycloak-service

    ports:
      - "8080:8080"

    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://localhost:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: Keycloak#123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    command: "start-dev"
