apiVersion: v1
kind: Pod

metadata:
  name: keycloak-iam-service
  labels:
    type: iam-service
    tier: backend-service

spec:
  containers:
    - name: keycloak-iam-service
      image: quay.io/keycloak/keycloak

      resources:
        limits:
          cpu: "256m"
          memory: "256Mi"

      ports:
        - containerPort: 8080

      env:
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: admin

      args:
        - start-dev