apiVersion: v1
kind: Service

metadata:
  name: spring-boot-kafka-microservice-load-balancer
  labels:
    type: load-balancer-service
    tier: backend

spec:
  # type of the service
  type: LoadBalancer

  # selector for the pods
  selector:
    type: microservice-pod
    tier: backend
  
  # port configuration
  ports:
    - port: 8080
      targetPort: 8080
